source: &git_test_release_source
    owner: ((git_owner))
    access-token: ((git_access_token))
    tag_filter: "paas_release-(.*)"
    order_by: version

resources:
  - name: git_test_frontend_release
    type: github-release
    source:
      <<: *git_test_release_source
      repository: ((git_repo))

  - name: cf
    type: cf
    source:
      api: ((paas_api))
      username: ((paas_username))
      password: ((paas_password))
      organization: ((paas_org))
      space: ((paas_space))
      skip_cert_check: false

  - name: omnibus
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: deploy_from_git_release

jobs:
  - name: push_app
    plan:
      - get: omnibus
      - get: git_test_frontend_release
        trigger: true
      - task: download_frontend_artifact
        file: omnibus/ci/tasks/download_deployment_artifact.yml
        input_mapping: { git_release: git_test_frontend_release }
        output_mapping: { artifact: frontend_artifact }
      - put: cf
        params:
          path: frontend_artifact
          manifest: frontend_artifact/manifest.yml
          vars_files: # when providing `path` the vars_file is relative to it.
            - ../omnibus/paas/env_variables/dev-dan.yml


