---
groups:
  - name: All
    jobs:
      - update-pipeline
      - card-payment-smoke-tests-staging
      - direct-debit-smoke-tests-staging
      - products-smoke-test-staging

  - name: Staging Deploys
    jobs:
      - deploy-adminusers-staging
      - deploy-cardid-staging
      - deploy-card-connector-staging
      - deploy-card-frontend-staging
      - deploy-directdebit-connector-staging
      - deploy-directdebit-frontend-staging
      - deploy-ledger-staging
      - deploy-products-staging
      - deploy-products-ui-staging
      - deploy-publicapi-staging
      - deploy-publicauth-staging
      - deploy-selfservice-staging
      - deploy-notifications-staging

  - name: Smoke Tests
    jobs:
      - deploy-selenium-hub
      - deploy-smoke-tests-staging
      - smoke-tests-staging-network-policies
      - smoke-test-user-staging
      - card-payment-smoke-tests-staging
      - direct-debit-smoke-tests-staging
      - products-smoke-test-staging

resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: omnibus
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: smoke-test-user

  - name: paas-staging
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.cloud.service.gov.uk
      org: govuk-pay
      space: staging
      username: ((paas-ireland-username))
      password: ((paas-ireland-password))

  - name: deploy-pipeline
    type: concourse-pipeline
    icon: pipe
    source:
      teams:
        - name: pay-deploy
          username: pay-deploy
          password: ((readonly_local_user_password))

  - &image
    name: adminusers
    type: docker-image
    icon: docker
    source: &image-source
      repository: govukpay/adminusers
      tag: latest-master
      username: ((docker-username))
      password: ((docker-password))

  - <<: *image
    name: cardid
    source:
      <<: *image-source
      repository: govukpay/cardid

  - <<: *image
    name: card-connector
    source:
      <<: *image-source
      repository: govukpay/connector

  - <<: *image
    name: directdebit-connector
    source:
      <<: *image-source
      repository: govukpay/directdebit-connector

  - <<: *image
    name: directdebit-frontend
    source:
      <<: *image-source
      repository: govukpay/directdebit-frontend

  - <<: *image
    name: card-frontend
    source:
      <<: *image-source
      repository: govukpay/frontend

  - <<: *image
    name: ledger
    source:
      <<: *image-source
      repository: govukpay/ledger

  - <<: *image
    name: products
    source:
      <<: *image-source
      repository: govukpay/products

  - <<: *image
    name: products-ui
    source:
      <<: *image-source
      repository: govukpay/products-ui

  - <<: *image
    name: publicapi
    source:
      <<: *image-source
      repository: govukpay/publicapi

  - <<: *image
    name: publicauth
    source:
      <<: *image-source
      repository: govukpay/publicauth

  - <<: *image
    name: selfservice
    source:
      <<: *image-source
      repository: govukpay/selfservice

  - <<: *image
    name: notifications
    source:
      <<: *image-source
      repository: govukpaypaas/notifications

  - name: paas-smoke-tests
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.cloud.service.gov.uk
      org: govuk-pay
      space: smoke-tests
      username: ((paas-ireland-username))
      password: ((paas-ireland-password))

  - name: endtoend-container
    type: registry-image
    icon: docker
    source:
      repository: govukpay/endtoend
      tag: latest-master
      username: ((docker-username))
      password: ((docker-password))

x-cf-creds: &cf-creds
  CF_API: https://api.cloud.service.gov.uk
  CF_USERNAME: ((paas-ireland-username))
  CF_PASSWORD: ((paas-ireland-password))
  CF_ORG: govuk-pay

jobs:
  - name: update-pipeline
    plan:
      - get: omnibus
        trigger: true
      - put: deploy-pipeline
        params:
          pipelines:
            - name: deploy
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy.yml

  - name: deploy-adminusers-staging
    serial_groups: [adminusers-stg]
    plan:
      - get: omnibus
      - get: adminusers
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params: &paas-app
          command: push
          app_name: adminusers
          manifest: omnibus/paas/pay-apps.yml
          docker_password: ((docker-password))
          vars:
            space: staging
            docker-username: ((docker-username))
          vars_files:
            - omnibus/paas/env_variables/staging.yml
      - &bind-db
        task: bind-db
        file: omnibus/ci/tasks/cf-task.yml
        input_mapping: { workdir: omnibus }
        params: &bind-db-params
          <<: *cf-creds
          CF_SPACE: staging
          CF_SPACE_CDE: staging-cde
          COMMAND: bind_db adminusers adminusers-db

  - name: deploy-cardid-staging
    serial_groups: [cardid-stg]
    plan:
      - get: omnibus
      - get: cardid
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: cardid
          space: staging-cde

  - name: deploy-card-connector-staging
    serial_groups: [card-connector-stg]
    plan:
      - get: omnibus
      - get: card-connector
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: card-connector
          space: staging-cde
      - <<: *bind-db
        params:
          <<: *bind-db-params
          CF_SPACE: staging-cde
          COMMAND: bind_db card-connector card-connector-db

  - name: deploy-card-frontend-staging
    serial_groups: [card-frontend-stg]
    plan:
      - get: omnibus
      - get: card-frontend
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: card-frontend
          space: staging-cde

  - name: deploy-directdebit-connector-staging
    serial_groups: [directdebit-connector-stg]
    plan:
      - get: omnibus
      - get: directdebit-connector
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: directdebit-connector
      - <<: *bind-db
        params:
          <<: *bind-db-params
          COMMAND: bind_db directdebit-connector directdebit-connector-db

  - name: deploy-directdebit-frontend-staging
    serial_groups: [directdebit-frontend-stg]
    plan:
      - get: omnibus
      - get: directdebit-frontend
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: directdebit-frontend

  - name: deploy-ledger-staging
    serial_groups: [ledger-stg]
    plan:
      - get: omnibus
      - get: ledger
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: ledger
      - <<: *bind-db
        params:
          <<: *bind-db-params
          COMMAND: bind_db ledger ledger-db

  - name: deploy-products-staging
    serial_groups: [products-stg]
    plan:
      - get: omnibus
      - get: products
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: products
      - <<: *bind-db
        params:
          <<: *bind-db-params
          COMMAND: bind_db products products-db

  - name: deploy-products-ui-staging
    serial_groups: [products-ui-stg]
    plan:
      - get: omnibus
      - get: products-ui
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: products-ui

  - name: deploy-publicapi-staging
    serial_groups: [publicapi-stg]
    plan:
      - get: omnibus
      - get: publicapi
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: publicapi

  - name: deploy-publicauth-staging
    serial_groups: [publicauth-stg]
    plan:
      - get: omnibus
      - get: publicauth
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: publicauth
      - <<: *bind-db
        params:
          <<: *bind-db-params
          COMMAND: bind_db publicauth publicauth-db

  - name: deploy-selfservice-staging
    serial_groups: [selfservice-stg]
    plan:
      - get: omnibus
      - get: selfservice
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: selfservice

  - name: deploy-notifications-staging
    serial_groups: [notifications-stg]
    plan:
      - get: omnibus
      - get: notifications
        trigger: true
        params:
          skip_download: true
      - put: app
        resource: paas-staging
        params:
          <<: *paas-app
          app_name: notifications

  - name: deploy-selenium-hub
    serial_groups: [selenium-stg]
    serial: true
    plan:
      - get: omnibus
      - put: paas-smoke-tests
        params: &push-app
          command: push
          app_name: selenium-hub
          manifest: omnibus/paas/smoke-test-apps.yml
          vars_files:
            - omnibus/paas/env_variables/staging-smoke-tests.yml

  - name: deploy-smoke-tests-staging
    serial_groups: [smoke-tests-stg]
    plan:
      - get: omnibus
      - get: endtoend-container
        trigger: true
      - put: paas-smoke-tests
        params:
          <<: *push-app
          docker_password: ((docker-password))
          docker_username: ((docker-username))
          docker_image: govukpay/endtoend:latest-master
          app_name: smoke-tests-staging

  - name: smoke-tests-staging-network-policies
    serial_groups: [selenium-stg, smoke-tests-stg]
    plan:
      - get: omnibus
        passed: [deploy-selenium-hub, deploy-smoke-tests-staging]
      - get: endtoend-container
        passed: [deploy-smoke-tests-staging]
        trigger: true
      - put: apply-network-policies
        resource: paas-smoke-tests
        params:
          command: add-network-policy
          source_app: smoke-tests-staging
          destination_app: selenium-hub
          port: 4444
          protocol: tcp

  - name: smoke-test-user-staging
    serial_groups:
      - card-connector-stg
      - directdebit-connector-stg
      - publicapi-stg
      - publicauth-stg
      - adminusers-stg
      - products-stg
      - smoke-tests-stg
    plan:
      - get: omnibus
      - get: endtoend-container
        passed: [deploy-smoke-tests-staging]
        trigger: true
      - task: create-service
        file: omnibus/ci/tasks/smoke-test-user.yml
        params:
          <<: *cf-creds
          CF_SPACE: staging
          CF_SPACE_CDE: staging-cde
          CF_SPACE_TOOLS: smoke-tests
          SMOKE_TEST_APP: smoke-tests-staging
          SERVICE_NAME: smoke-test-user-staging

  - name: card-payment-smoke-tests-staging
    serial_groups: [cardid-stg, card-connector-stg, card-frontend-stg, ledger-stg, publicapi-stg, publicauth-stg]
    plan:
      - get: omnibus
      - get: endtoend-container
        passed: [deploy-smoke-tests-staging, smoke-test-user-staging]
        trigger: true
      - &trigger-test
        get: cardid
        passed: [deploy-cardid-staging]
        trigger: true
        params:
          skip_download: true
      - <<: *trigger-test
        get: card-connector
        passed: [deploy-card-connector-staging]
      - <<: *trigger-test
        get: card-frontend
        passed: [deploy-card-frontend-staging]
      - <<: *trigger-test
        get: ledger
        passed: [deploy-ledger-staging]
      - <<: *trigger-test
        get: publicapi
        passed: [deploy-publicapi-staging]
      - <<: *trigger-test
        get: publicauth
        passed: [deploy-publicauth-staging]
      - task: run card smoke test
        file: omnibus/ci/tasks/cf-task.yml
        params: &smoke-test-params
          <<: *cf-creds
          CF_SPACE: smoke-tests
          COMMAND: cf ssh smoke-tests-staging -c /app/bin/smoke-cardp1

  - name: direct-debit-smoke-tests-staging
    serial_groups: [adminusers-stg, directdebit-connector-stg, directdebit-frontend-stg, ledger-stg, publicapi-stg, publicauth-stg]
    plan:
      - get: omnibus
      - get: endtoend-container
        passed: [deploy-smoke-tests-staging, smoke-test-user-staging]
        trigger: true
      - <<: *trigger-test
        get: adminusers
        passed: [deploy-adminusers-staging]
      - <<: *trigger-test
        get: directdebit-connector
        passed: [deploy-directdebit-connector-staging]
      - <<: *trigger-test
        get: directdebit-frontend
        passed: [deploy-directdebit-frontend-staging]
      - <<: *trigger-test
        get: ledger
        passed: [deploy-ledger-staging]
      - <<: *trigger-test
        get: publicapi
        passed: [deploy-publicapi-staging]
      - <<: *trigger-test
        get: publicauth
        passed: [deploy-publicauth-staging]
      - task: run direct debit smoke test
        file: omnibus/ci/tasks/cf-task.yml
        params:
          <<: *smoke-test-params
          COMMAND: cf ssh smoke-tests-staging -c /app/bin/smoke-directdebitp1

  - name: products-smoke-test-staging
    serial_groups: [products-stg, products-ui-stg]
    plan:
      - get: omnibus
      - get: endtoend-container
        passed: [deploy-smoke-tests-staging, smoke-test-user-staging]
        trigger: true
      - <<: *trigger-test
        get: products
        passed: [deploy-products-staging]
      - <<: *trigger-test
        get: products-ui
        passed: [deploy-products-ui-staging]
      - task: run products smoke test
        file: omnibus/ci/tasks/cf-task.yml
        params:
          <<: *smoke-test-params
          COMMAND: cf ssh smoke-tests-staging -c /app/bin/smoke-products
