---
x-templates:
  x-repo: &repo
    name: repo
    type: git
    icon: github-circle
    source: &repo-source
      uri: some-uri
      branch: master
      username: ((github-username))
      password: ((github-password))
  x-create-app: &create-app
    task: create-app
    file: omnibus/ci/tasks/create-app.yml
    params: &create-app-params
      CF_ORG: govuk-pay
      CF_SPACE: ((space))
      APP: app
  x-paas-app: &paas-app
    command: push
    app_name: adminusers
    manifest: omnibus/paas/pay-apps.yml
    docker_password: ((docker-password))
    vars:
      space: ((space))
      docker-username: ((docker-username))
    vars_files:
      - omnibus/paas/env_variables/((environment)).yml
  x-java-app: &java-app
    <<: *paas-app
    path: src/target/*-allinone.jar
  x-node-app: &node-app
    <<: *paas-app
    path: src

resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: omnibus
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: buildpackery

  - name: paas
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.london.cloud.service.gov.uk
      org: govuk-pay
      space: ((space))
      username: ((cf-username))
      password: ((cf-password))

  - <<: *repo
    name: adminusers
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-adminusers

  - <<: *repo
    name: cardid
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-cardid

  - <<: *repo
    name: cardid-data
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-cardid-data

  - <<: *repo
    name: card-connector
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-connector

  - <<: *repo
    name: card-frontend
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-frontend

  - <<: *repo
    name: directdebit-connector
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-direct-debit-connector

  - <<: *repo
    name: directdebit-frontend
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-direct-debit-frontend

  - <<: *repo
    name: ledger
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-ledger

  - <<: *repo
    name: products
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-products

  - <<: *repo
    name: products-ui
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-products-ui

  - <<: *repo
    name: publicapi
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-publicapi

  - <<: *repo
    name: publicauth
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-publicauth

  - <<: *repo
    name: selfservice
    source:
      <<: *repo-source
      uri: https://github.com/alphagov/pay-selfservice

jobs:
  - name: provision-space
    serial: true
    plan:
      - get: omnibus
        trigger: true
      - task: create-users
        file: omnibus/ci/tasks/create-users.yml
        params:
          SPACE: ((space))
      - put: space
        resource: paas
        params:
          commands:
            - command: create-space
            - command: create-users-from-file
              file: out/users.csv
      - in_parallel:
        - <<: *create-app
          task: create-adminusers
          params:
            <<: *create-app-params
            APP: adminusers
        - <<: *create-app
          task: create-cardid
          params:
            <<: *create-app-params
            APP: cardid
        - <<: *create-app
          task: create-card-frontend
          params:
            <<: *create-app-params
            APP: card-frontend
        - <<: *create-app
          task: create-card-connector
          params:
            <<: *create-app-params
            APP: card-connector
        - <<: *create-app
          task: create-directdebit-frontend
          params:
            <<: *create-app-params
            APP: directdebit-frontend
        - <<: *create-app
          task: create-directdebit-connector
          params:
            <<: *create-app-params
            APP: directdebit-connector
        - <<: *create-app
          task: create-ledger
          params:
            <<: *create-app-params
            APP: ledger
        - <<: *create-app
          task: create-products
          params:
            <<: *create-app-params
            APP: products
        - <<: *create-app
          task: create-products-ui
          params:
            <<: *create-app-params
            APP: products-ui
        - <<: *create-app
          task: create-publicapi
          params:
            <<: *create-app-params
            APP: publicapi
        - <<: *create-app
          task: create-publicauth
          params:
            <<: *create-app-params
            APP: publicauth
        - <<: *create-app
          task: create-selfservice
          params:
            <<: *create-app-params
            APP: selfservice
        - <<: *create-app
          task: create-egress
          params:
            <<: *create-app-params
            APP: egress
            TYPE: docker
        - <<: *create-app
          task: create-postgres
          params:
            <<: *create-app-params
            APP: postgres
            TYPE: docker
        - <<: *create-app
          task: create-sqs
          params:
            <<: *create-app-params
            APP: sqs
            TYPE: docker
      - task: apply-network-policies
        file: omnibus/ci/tasks/apply-network-policies.yml
        params:
          CF_ORG: govuk-pay
          CF_SPACE: ((space))
          POLICIES_FILE: omnibus/paas/network-policies.yml

  - name: delete-space
    plan:
      - put: paas
        params:
          command: delete-space

  - name: deploy-adminusers
    serial_groups: [adminusers]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: adminusers
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params: &java-app
          app_name: adminusers

  - name: deploy-cardid
    serial_groups: [cardid]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: cardid
        trigger: true
        params:
          submodules: none
      - get: cardid-data
        trigger: true
      - task: copy-cardid-data
        file: omnibus/ci/tasks/copy-cardid-data.yaml
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: cardid

  - name: deploy-card-connector
    serial_groups: [card-connector]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: card-connector
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: card-connector

  - name: deploy-card-frontend
    serial_groups: [card-frontend]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: card-frontend
        trigger: true
      - task: test
        file: omnibus/ci/tasks/frontend.yaml
      - put: app
        resource: paas
        params:
          <<: *node-app
          app_name: card-frontend

  - name: deploy-directdebit-connector
    serial_groups: [directdebit-connector]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: directdebit-connector
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: directdebit-connector

  - name: deploy-directdebit-frontend
    serial_groups: [directdebit-frontend]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: directdebit-frontend
        trigger: true
      - task: test
        file: omnibus/ci/tasks/frontend.yaml
      - put: app
        resource: paas
        params:
          <<: *node-app
          app_name: directdebit-frontend

  - name: deploy-ledger
    serial_groups: [ledger]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: ledger
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: ledger

  - name: deploy-products
    serial_groups: [products]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: products
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: products

  - name: deploy-products-ui
    serial_groups: [products-ui]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: products-ui
        trigger: true
      - task: build
        file: omnibus/ci/tasks/frontend.yaml
      - put: app
        resource: paas
        params:
          <<: *node-app
          app_name: products-ui

  - name: deploy-publicapi
    serial_groups: [publicapi]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: publicapi
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: publicapi

  - name: deploy-publicauth
    serial_groups: [publicauth]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: publicauth
        trigger: true
      - task: build
        file: omnibus/ci/tasks/maven-build.yaml
      - put: app
        resource: paas
        params:
          <<: *java-app
          app_name: publicauth

  - name: deploy-selfservice
    serial_groups: [selfservice]
    plan:
      - get: omnibus
        passed: [provision-space, deploy-tools]
        trigger: true
      - get: src
        resource: selfservice
        trigger: true
      - task: build
        file: omnibus/ci/tasks/frontend.yaml
      - put: app
        resource: paas
        params:
          <<: *node-app
          app_name: selfservice

  - name: deploy-tools
    serial_groups: [tools]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - put: egress
        resource: paas
        params:
          <<: *paas-app
          app_name: egress
      - put: sqs
        resource: paas
        params:
          <<: *paas-app
          app_name: sqs
      - put: postgres
        resource: paas
        params:
          <<: *paas-app
          app_name: postgres
