---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: omnibus
    type: git
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: develop

  - name: paas
    type: cf-cli
    source:
      api: https://api.london.cloud.service.gov.uk
      org: govuk-pay
      space: dev-((developer))
      username: ((cf-username))
      password: ((cf-password))

  - name: adminusers
    type: registry-image
    source: &image-source
      repository: govukpay/adminusers
      tag: latest-master
      username: ((docker-username))
      password: ((docker-password))

  - name: cardid
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/cardid

  - name: card-connector
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/connector

  - name: directdebit-connector
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/directdebit-connector

  - name: directdebit-frontend
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/directdebit-frontend

  - name: card-frontend
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/frontend

  - name: ledger
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/ledger

  - name: products
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/products

  - name: products-ui
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/products-ui

  - name: publicapi
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/publicapi

  - name: publicauth
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/publicauth

  - name: selfservice
    type: registry-image
    source:
      <<: *image-source
      repository: govukpay/selfservice

jobs:
  - name: provision-space
    plan:
      - get: omnibus
        trigger: true
      - task: create-users
        file: omnibus/ci/tasks/create-users.yml
        params:
          SPACE: dev-((developer))
          USER: ((user))
      - put: space
        resource: paas
        params:
          commands:
            - command: create-space
            - command: create-users-from-file
              file: out/users.csv

  - name: deploy-adminusers
    serial_groups: [adminusers, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: adminusers
        trigger: true
      - put: app
        resource: paas
        params: &paas-app
          command: push
          app_name: adminusers
          manifest: omnibus/paas/pay-apps.yml
          no_start: true
          docker_password: ((docker-password))
          vars:
            developer: ((developer))
            docker-username: ((docker-username))

  - name: deploy-cardid
    serial_groups: [cardid, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: cardid
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: cardid

  - name: deploy-card-connector
    serial_groups: [card-connector, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: card-connector
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: card-connector

  - name: deploy-card-frontend
    serial_groups: [card-frontend, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: card-frontend
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: card-frontend

  - name: deploy-directdebit-connector
    serial_groups: [directdebit-connector, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: directdebit-connector
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: directdebit-connector

  - name: deploy-directdebit-frontend
    serial_groups: [directdebit-frontend, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: directdebit-frontend
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: directdebit-frontend

  - name: deploy-ledger
    serial_groups: [ledger, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: ledger
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: ledger

  - name: deploy-products
    serial_groups: [products, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: products
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: products

  - name: deploy-products-ui
    serial_groups: [products-ui, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: products-ui
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: products-ui

  - name: deploy-publicapi
    serial_groups: [publicapi, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: publicapi
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: publicapi

  - name: deploy-publicauth
    serial_groups: [publicauth, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: publicauth
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: publicauth

  - name: deploy-selfservice
    serial_groups: [selfservice, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - get: selfservice
        trigger: true
      - put: app
        resource: paas
        params:
          <<: *paas-app
          app_name: selfservice

  - name: deploy-tools
    serial_groups: [tools, michaelangelo]
    plan:
      - get: omnibus
        passed: [provision-space]
        trigger: true
      - put: egress
        resource: paas
        params:
          <<: *paas-app
          app_name: egress
      - put: sqs
        resource: paas
        params:
          <<: *paas-app
          app_name: sqs
      - put: postgres
        resource: paas
        params:
          <<: *paas-app
          app_name: postgres
