---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: omnibus
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: master

  - name: omnibus-paas
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: master
      paths:
        - paas

  - name: paas-london
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.london.cloud.service.gov.uk
      org: govuk-pay
      space: ((space))
      username: ((cf-username))
      password: ((cf-password))

  - &image
    name: adminusers
    type: registry-image
    icon: docker
    source: &image-source
      repository: govukpay/adminusers
      tag: latest-master
      username: ((docker-username))
      password: ((docker-password))

  - <<: *image
    name: cardid
    source:
      <<: *image-source
      repository: govukpay/cardid

  - <<: *image
    name: card-connector
    source:
      <<: *image-source
      repository: govukpay/connector

  - <<: *image
    name: directdebit-connector
    source:
      <<: *image-source
      repository: govukpay/directdebit-connector

  - <<: *image
    name: directdebit-frontend
    source:
      <<: *image-source
      repository: govukpay/directdebit-frontend

  - <<: *image
    name: card-frontend
    source:
      <<: *image-source
      repository: govukpay/frontend

  - <<: *image
    name: ledger
    source:
      <<: *image-source
      repository: govukpay/ledger

  - <<: *image
    name: products
    source:
      <<: *image-source
      repository: govukpay/products

  - <<: *image
    name: products-ui
    source:
      <<: *image-source
      repository: govukpay/products-ui

  - <<: *image
    name: publicapi
    source:
      <<: *image-source
      repository: govukpay/publicapi

  - <<: *image
    name: publicauth
    source:
      <<: *image-source
      repository: govukpay/publicauth

  - <<: *image
    name: selfservice
    source:
      <<: *image-source
      repository: govukpay/selfservice

  - <<: *image
    name: notifications
    source:
      <<: *image-source
      repository: govukpaypaas/notifications

jobs:
  - name: create-space
    serial_groups: [create-space]
    plan:
      - get: omnibus
      - put: create-space
        resource: paas-london
        params:
          command: create-space
          space: ((space))
      - put: set-permissions
        resource: paas-london
        params:
          command: create-users-from-file
          file: omnibus/ci/config/space-users/((space)).csv

  - name: provision-space
    serial_groups: [create-space]
    plan:
      - get: omnibus
        passed: [create-space]
      - get: omnibus-paas
        trigger: true
      - task: provision-space
        file: omnibus/ci/tasks/cf-task.yml
        input_mapping: { workdir: omnibus-paas }
        params:
          CF_ORG: govuk-pay
          CF_SPACE: ((space))
          COMMAND: workdir/paas/provision_space.sh
          DEPLOYER_USER: ((cf-username))
          DOCKER_APPS: 'true'

  - name: create-test-user
    serial_groups:
      - tools
      - card-connector
      - directdebit-connector
      - publicapi
      - publicauth
      - adminusers
      - products
    plan:
      - get: omnibus
        resource: omnibus-paas
        trigger: true
        passed: [deploy-tools]
      - get: card-connector
        passed: [deploy-card-connector]
      - get: directdebit-connector
        passed: [deploy-directdebit-connector]
      - get: publicapi
        passed: [deploy-publicapi]
      - get: publicauth
        passed: [deploy-publicauth]
      - get: adminusers
        passed: [deploy-adminusers]
      - get: products
        passed: [deploy-products]
      - task: run-client
        file: omnibus/ci/tasks/test-client.yml
        params:
          CF_ORG: govuk-pay
          CF_SPACE: ((space))
          ARGS: user a-test-user Service

  - name: deploy-adminusers
    serial_groups: [adminusers]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: adminusers
        trigger: true
      - put: app
        resource: paas-london
        params: &paas-app
          command: push
          app_name: adminusers
          manifest: omnibus/paas/pay-apps.yml
          docker_password: ((docker-password))
          vars:
            space: ((space))
            docker-username: ((docker-username))
            http_proxy_host: egress-((space)).apps.internal
            publicapi_url: pay-publicapi-((space)).london.cloudapps.digital
            publicauth_url: pay-publicauth-((space)).london.cloudapps.digital
            selfservice_url: pay-selfservice-((space)).london.cloudapps.digital
            card_frontend_url: pay-card-frontend-((space)).london.cloudapps.digital
            directdebit_frontend_url: pay-directdebit-frontend-((space)).london.cloudapps.digital
            notifications_url: pay-notifications-((space)).london.cloudapps.digital
            products_ui_url: pay-products-ui-((space)).london.cloudapps.digital
          vars_files:
            - omnibus/paas/env_variables/((environment)).yml

  - name: deploy-cardid
    serial_groups: [cardid]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: cardid
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: cardid

  - name: deploy-card-connector
    serial_groups: [card-connector]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: card-connector
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: card-connector

  - name: deploy-card-frontend
    serial_groups: [card-frontend]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: card-frontend
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: card-frontend

  - name: deploy-directdebit-connector
    serial_groups: [directdebit-connector]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: directdebit-connector
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: directdebit-connector

  - name: deploy-directdebit-frontend
    serial_groups: [directdebit-frontend]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: directdebit-frontend
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: directdebit-frontend

  - name: deploy-ledger
    serial_groups: [ledger]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: ledger
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: ledger

  - name: deploy-products
    serial_groups: [products]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: products
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: products

  - name: deploy-products-ui
    serial_groups: [products-ui]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: products-ui
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: products-ui

  - name: deploy-publicapi
    serial_groups: [publicapi]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: publicapi
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: publicapi

  - name: deploy-publicauth
    serial_groups: [publicauth]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: publicauth
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: publicauth

  - name: deploy-selfservice
    serial_groups: [selfservice]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: selfservice
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: selfservice

  - name: deploy-notifications
    serial_groups: [notifications]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [deploy-tools]
        trigger: true
      - get: notifications
        trigger: true
      - put: app
        resource: paas-london
        params:
          <<: *paas-app
          app_name: notifications

  - name: deploy-tools
    serial_groups: [tools]
    plan:
      - get: omnibus
        resource: omnibus-paas
        passed: [provision-space]
        trigger: true
      - put: egress
        resource: paas-london
        params:
          <<: *paas-app
          app_name: egress
      - put: sqs
        resource: paas-london
        params:
          <<: *paas-app
          app_name: sqs
      - put: postgres
        resource: paas-london
        params:
          <<: *paas-app
          app_name: postgres
