---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: omnibus
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: master
      path: ci

  - name: dev-pipelines
    type: concourse-pipeline
    icon: pipe
    source:
      target: ((concourse-url))
      teams:
        - name: pay-deploy
          username: pay-deploy
          password: ((readonly_local_user_password))

jobs:
  - name: update-pipelines
    plan:
      - get: omnibus
        trigger: true
      - put: dev-pipelines
        params:
          pipelines_file: omnibus/ci/config/dev-pipelines.yml
