---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: omnibus
    type: git
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: develop

  - name: pay-pipelines
    type: concourse-pipeline
    source:
      target: ((concourse-url))
      teams:
        - name: pay-deploy
          username: pay-deploy
          password: ((readonly_local_user_password))

jobs:
  - name: update-pipelines
    plan:
      - get: omnibus
        trigger: true
      - put: pay-pipelines
        params:
          pipelines:
            - name: provision-envs
              team: pay-deploy
              config_file: omnibus/ci/pipelines/provision-envs.yml
              vars:
                concourse-url: ((concourse-url))
            - name: dev-env-anshul
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-anshul
                environment: dev
            - name: dev-env-richard
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-richard
                environment: dev
            - name: dev-env-dan
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-dan
                environment: dev
            - name: dev-env-dom
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-dom
                environment: dev
            - name: dev-env-nim
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-nim
                environment: dev
            - name: dev-env-oswald
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-oswald
                environment: dev
            - name: dev-env-stephen
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: dev-stephen
                environment: dev
            - name: staging
              team: pay-deploy
              config_file: omnibus/ci/pipelines/deploy-env.yml
              vars:
                space: staging
                environment: staging
