---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: omnibus
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/pay-omnibus
      branch: paas-provision-space-script

  - name: paas-smoke-tests
    type: cf-cli
    icon: cloud-upload-outline
    source:
      api: https://api.cloud.service.gov.uk
      org: govuk-pay
      space: smoke-tests
      username: ((paas-ireland-username))
      password: ((paas-ireland-password))

  - name: endtoend-container
    type: registry-image
    icon: docker
    source:
      repository: govukpay/endtoend
      tag: latest-master
      username: ((docker-username))
      password: ((docker-password))

jobs:
  - name: deploy-selenium-hub
    serial_groups: [selenium-setup]
    serial: true
    plan:
      - get: omnibus
      - put: paas-tools
        params: &push-app
          command: push
          app_name: selenium-hub
          manifest: omnibus/paas/smoke-test-apps.yml
          vars_files:
            - omnibus/paas/env_variables/staging-smoke-tests.yml

  - name: deploy-endtoend
    plan:
      - get: omnibus
      - get: endtoend-container
        trigger: true
      - put: paas-tools
        params:
          <<: *push-app
          docker_password: ((docker-password))
          docker_username: ((docker-username))
          docker_image: govukpay/endtoend:latest-master
          app_name: endtoend

  - name: network-policies
    plan:
      - get: omnibus
        passed: [deploy-selenium-hub, deploy-endtoend]
      - put: network-policy-endtoend-selenium-hub
        resource: paas-tools
        params:
          command: add-network-policy
          source_app: endtoend
          destination_app: selenium-hub
          port: 4444
          protocol: tcp

  - name: start-selenium
    serial_groups: [selenium-setup]
    serial: true
    plan:
      - put: start selenium hub
        resource: paas-tools
        params:
          command: start
          app_name: selenium-hub

  - name: stop-selenium
    serial_groups: [selenium-setup]
    serial: true
    plan:
      - put: stop selenium hub
        resource: paas-tools
        params:
          command: stop
          app_name: selenium-hub
