language: minimal
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-pip python3-setuptools

install:
  - sudo python3 -m pip install pre-commit

script:
  - pre-commit run --source $(git rev-parse $TRAVIS_BRANCH) --origin $TRAVIS_COMMIT
