platform: linux

image_resource:
  type: registry-image
  source:
    repository: governmentpaas/cf-cli
    tag: cf7

inputs:
  - name: omnibus
    optional: true
  - name: artefact
    optional: true

params:
  CF_API: https://api.london.cloud.service.gov.uk
  CF_USERNAME: ((cf-username))
  CF_PASSWORD: ((cf-password))
  CF_ORG:
  CF_SPACE:
  MANIFEST_PATH: artefact
  MANIFEST_FILE: manifest.yml
  APP_NAME:
  PATH: artefact
  VARS_FILE:
  ZDT:

run:
  path: bash
  args:
    - -c
    - |
      set -o errexit -o nounset
      cf login -a "$CF_API" \
        -u "$CF_USERNAME" -p "$CF_PASSWORD" \
        -o "$CF_ORG" -s "$CF_SPACE"

      args=()
      args+=("$APP_NAME")
      args+=(--path "$PATH")
      args+=(--manifest "$MANIFEST_PATH/$MANIFEST_FILE")
      [ -n "$VARS_FILE" ] && args+=(--vars-file "$VARS_FILE")
      [ -n "$ZDT" ] && args+=(--strategy rolling)

      cf push "${args[@]}"
