platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

inputs:
  - name: src
  - name: cardid-data

outputs:
  - name: src

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o xtrace
      mkdir -p pay-cardid/data
      cp -r pay-cardid-data/* pay-cardid/data/
