platform: linux

image_resource:
  type: docker-image
  source: { repository: governmentpaas/cf-cli }

params:
  SPACE:
  ORG: govuk-pay

inputs:
  - name: omnibus

outputs:
  - name: out

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o nounset
      envsubst < omnibus/ci/config/space-users/$SPACE.csv > out/users.csv

