platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

inputs:
  - name: git-release
    optional: false

outputs:
  - name: artifact

run:
  path: sh
  args:
    - -c
    - |
      tar -C artifact -xf git-release/pay-*-*.tar.gz
