platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

inputs:
  - name: git-release
    optional: false

outputs:
  - name: artefact

run:
  path: sh
  args:
    - -c
    - |
      tar -C artefact -xf git-release/pay-*.tar.gz
