container_limits: {}
platform: linux

image_resource:
  type: registry-image
  source:
    repository: amidos/dcind

caches:
  - path: src/.m2

inputs:
  - name: src

run:
  path: bash
  args:
  - -ec
  - |
    apk --no-cache add openjdk11 maven --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

    source /docker-lib.sh
    start_docker

    cd src

    export MAVEN_HOME=/usr/lib/mvn
    export PATH=$MAVEN_HOME/bin:$PATH
    export MAVEN_REPO="$PWD/.m2"

    cat <<'EOF' >settings.xml
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <localRepository>${env.MAVEN_REPO}</localRepository>
    </settings>
    EOF

    mvn --global-settings settings.xml clean verify
