platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.1

inputs:
  - name: src

outputs:
  - name: src

caches:
  - path: .m2

run:
  path: bash
  dir: src
  args:
    - -c
    - |
      set -o errexit -o nounset -o pipefail
      mvn test
      mvn -Dmaven.repo.local=.m2 -Dmaven.test.skip=true -DskipTests package
