platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: 12.14-alpine

inputs:
  - name: src
  - name: release-info

outputs:
  - name: build-output

caches:
  - path: node_module_cache_dev
  - path: node_module_cache_prod

params:
  LD_LIBRARY_PATH: /src/node_modules/appmetrics
  APP_NAME: app

run:
  path: sh
  dir: src
  args:
    - -ec
    - |
      set -o errexit -o nounset -o pipefail
      node --version
      npm --version
      apk add --virtual build-dependencies --update python build-base libexecinfo-dev
      ln -s ../node_module_cache_dev node_modules
      npm rebuild node-sass
      npm install
      npm run compile
      rm node_modules
      ln -s ../node_module_cache_prod node_modules
      npm install --only=prod

      release_number="$(cat ../release-info/number)"
      archive_path="../build-output/${APP_NAME}-${release_number}.tar.gz"

      echo "Creating build archive in: ${archive_path}"
      tar -czfh "$archive_path" --exclude .git .
