container_limits: {}
platform: linux
image_resource:
  type: registry-image
  source:
    repository: govukpay/concourse-runner
params:
  provider:
  consumer:
inputs:
  - name: pact_params
  - name: test_target
run:
  path: sh
  args:
    - -ec
    - |

      function cleanup {
        echo "CLEANUP TRIGGERED"
        clean_docker
        stop_docker
        echo "CLEANUP COMPLETE"
      }

      function needsVerification() {
        grep "^${provider}" pact_params/requirements.txt || test -f pact_params/verification_needed
      }

      trap cleanup EXIT
      source /docker-helpers.sh

      if ! needsVerification; then
        echo "All pacts already verified"
        exit 0
      fi


      start_docker

      set -x

      consumer_tag="$(cat pact_params/consumer_tag)"
      provider_version="$(git rev-parse HEAD)"

      cd test_target

      mvn test \
        -DrunContractTests \
        -DCONSUMER="$consumer" \
        -DPACT_CONSUMER_TAG="$consumer_tag" \
        -Dpact.provider.version="$provider_version" \
        -Dpact.verifier.publishResults=true \
        -DPACT_BROKER_HOST=pay-concourse-pact-broker.cloudapps.digital \
        -DPACT_BROKER_USERNAME=b \
        -DPACT_BROKER_PASSWORD=a
