platform: linux
image_resource:
  type: registry-image
  source:
    repository: curlimages/curl
inputs:
  - name: pacts
  - name: git_details
params:
  consumer_name:
run:
  path: sh
  args:
    - -c
    - |

      if [ ! -f git_details/head_sha ]; then
        echo "ERROR: git_details/head_sha does not exist."
        exit 1
      fi

      version="$(cat git_details/head_sha)"

      # This doesn't check the response from pact broker so passes when it fails
      # we should fix that.
      for pact in $(ls pacts | grep -v '\-to\-'); do
        provider_name=$(echo $pact | awk -F "-" '{ print $2}'| sed 's/.json//')
        curl -v -X PUT -H "Content-Type: application/json" \
        -d@$pact \
        https://pay-concourse-pact-broker.cloudapps.digital/pacts/provider/$provider_name/consumer/$consumer_name/version/$version
      done
