platform: linux
image_resource:
  type: registry-image
  source:
    repository: curlimages/curl
inputs:
  - name: build
params:
  consumer_name:
  pact_directory:
run:
  path: sh
  dir: build
  args:
    - -c
    - |

      if [ ! -f .git/resource/head_sha ]; then
        echo "ERROR: .git/resource/head_sha/ does not exist."
        exit 1
      fi

      version="$(cat .git/resource/head_sha)"
      cd "$pact_directory"
      for pact in `ls . | grep -v '\-to\-' `; do
        provider_name=$(echo $pact | awk -F "-" '{ print $2}'| sed 's/.json//')
        curl -v -X PUT -H "Content-Type: application/json" \
        -d@$pact \
        https://pay-concourse-pact-broker.cloudapps.digital/pacts/provider/$provider_name/consumer/$consumer_name/version/$version
      done
