platform: linux

image_resource:
  type: docker-image
  source: { repository: governmentpaas/cf-cli }

params:
  CF_USERNAME: ((cf-username))
  CF_PASSWORD: ((cf-password))
  CF_ORG:
  CF_SPACE:
  NOTIFICATIONS_URL:

run:
  path: bash
  args:
    - -c
    - |
      set -o nounset
      cf login -a https://api.london.cloud.service.gov.uk \
        -u "$CF_USERNAME" -p "$CF_PASSWORD" \
        -o "$CF_ORG" -s "$CF_SPACE"

      httpcode=$(cf ssh endtoend -c "curl -s --write-out '%{http_code}\n' --fail -X POST -H 'Content-Type: application/json' -d '{"content_for" : "naxsi_rules"}' "${NOTIFICATIONS_URL}"")
      echo "$0: $NOTIFICATIONS_URL responded with status code '$httpcode'"

      if [ "$httpcode" != 200 ]; then
        exit 1
      fi
