# Runs smoke tests in a Concourse task using endtoend docker container
# See: https://github.com/alphagov/pay-scripts/blob/master/jenkins/run-smoke.sh
platform: linux

image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
    tag: latest

inputs:
  - name: e2e-runner
  - name: selenium

params:
  SMOKE_TEST:
  PUBLICAPI_URL:
  SELFSERVICE_URL:
  SELENIUM_HUB_URL:
  WEB_DRIVER: CHROME_REMOTE
  CHROME_DRIVER_PATH: /usr/bin/chromedriver
  HTTP_ZAP_ENABLED: 'false'

run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      docker load -i e2e-runner/image
      docker load -i selenium/image
      docker images
