---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: govukpay/pay-concourse-utilities
    username: ((docker-username))
    password: ((docker-password))
    tag: latest

params:
  HOSTED_GRAPHITE_ACCOUNT_ID: ((HOSTED_GRAPHITE_ACCOUNT_ID))
  HOSTED_GRAPHITE_API_KEY: ((HOSTED_GRAPHITE_API_KEY))
  METRIC_NAME: metricname
  METRIC_VALUE: metricvalue

run:
  path: bash
  dir: src
  args:
    - -euc
    - |
      echo "Sending metric ${METRIC_NAME}"
      nc -w 2 "${HOSTED_GRAPHITE_ACCOUNT_ID}.carbon.hostedgraphite.com" 2003 <<< "${HOSTED_GRAPHITE_API_KEY}.${METRIC_NAME} ${METRIC_VALUE}"
