platform: linux

image_resource:
  type: docker-image
  source: { repository: governmentpaas/cf-cli }

inputs:
  - name: omnibus

params:
  CF_USERNAME: ((cf-username))
  CF_PASSWORD: ((cf-password))
  CF_ORG:
  CF_SPACE:
  ARGS:

run:
  path: bash
  dir: omnibus/client
  args:
    - -c
    - |
      set -o errexit -o nounset
      gem install bundler
      bundle install
      cf login -a https://api.london.cloud.service.gov.uk \
        -u "$CF_USERNAME" -p "$CF_PASSWORD" \
        -o "$CF_ORG" -s "$CF_SPACE"
      bundle exec ./client $ARGS
