---
groups:
  - name: all
    jobs:
      - deploy-admin-users
      - deploy-card-id
      - deploy-connector
      - deploy-direct-debit-connector
      - deploy-direct-debit-frontend
      - deploy-frontend
      - deploy-ledger
      - deploy-products-ui
      - deploy-products
      - deploy-public-api
      - deploy-public-auth
      - deploy-self-service
      - deploy-stubs
      - deploy-tools
      - switch-off-dev-env
      - stop-all-apps
      - restart-all-apps
  - name: deploy
    jobs:
      - deploy-admin-users
      - deploy-card-id
      - deploy-connector
      - deploy-direct-debit-connector
      - deploy-direct-debit-frontend
      - deploy-frontend
      - deploy-ledger
      - deploy-products-ui
      - deploy-products
      - deploy-public-api
      - deploy-public-auth
      - deploy-self-service
      - deploy-stubs
      - deploy-tools
  - name: operations
    jobs:
      - create-dev-env
      - switch-off-dev-env
      - stop-all-apps
      - restart-all-apps

resource_types:
  - name: fly
    type: docker-image
    source:
      repository: troykinsella/concourse-fly-resource
      tag: 2.0.1

  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource
      tag: latest

resources:
  - name: deploy-config
    type: git
    source:
      uri: https://github.com/alphagov/pay-gsp-pipelines
      branch: develop-andy
      paths:
        - manifests
        - tasks
  - name: every-night-at-6pm
    type: time
    source:
      start: 18:00
      stop: 18:30
      location: Europe/London
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: andy-paas-space
    type: cf-cli
    source:
      api: https://api.london.cloud.service.gov.uk
      org: govuk-pay
      space: andy
      username: ((cf-username))
      password: ((cf-password))

  - name: andy-dev-env-pipeline
    type: fly
    source:
      url: https://cd.gds-reliability.engineering
      username: pay-deploy
      password: ((readonly_local_user_password))
      team: pay-deploy

  - name: admin-users
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/adminusers
  - name: card-id
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/cardid
  - name: connector
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/connector
  - name: direct-debit-connector
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/dd-connector
  - name: direct-debit-frontend
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/dd-frontend
  - name: frontend
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/frontend
  - name: ledger
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/ledger
  - name: products-ui
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/products-ui
  - name: products
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/products
  - name: public-api
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/publicapi
  - name: public-auth
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/publicauth
  - name: self-service
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/selfservice

  - name: demo-service
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/demo-service
  - name: stubs
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/stubs
  - name: end-to-end
    type: docker-image
    icon: docker
    source:
      repository: registry.london.portfolio.govsvc.uk/pay/endtoend

  - name: egress
    type: docker-image
    icon: docker
    source:
      repository: govukpay/egress
      tag: latest-master
  - name: postgres
    type: docker-image
    icon: docker
    source:
      repository: postgres
  - name: sqs
    type: docker-image
    icon: docker
    source:
      repository: roribio16/alpine-sqs
  - name: selenium-hub
    type: docker-image
    icon: docker
    source:
      repository: selenium/hub
      tag: 3.9.1-actinium
  - name: chrome
    type: docker-image
    icon: docker
    source:
      repository: selenium/node-chrome
      tag: 3.9.1-actinium

jobs:
  - name: create-dev-env
    serial: true
    plan:
      # Due to a bug in CF, we need to create these first
      - task: create-internal-routes
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: cf7
          params:
            CF_USERNAME: ((cf-username))
            CF_PASSWORD: ((cf-password))
          run:
            path: bash
            args:
            - -c
            - |
              cf login -a https://api.london.cloud.service.gov.uk \
                -u $CF_USERNAME -p $CF_PASSWORD \
                -o govuk-pay -s andy
              cf create-route apps.internal --hostname admin-users
              cf create-route apps.internal --hostname card-id
              cf create-route apps.internal --hostname connector
              cf create-route apps.internal --hostname egress
              cf create-route apps.internal --hostname postgres
              cf create-route apps.internal --hostname sqs
              cf create-route apps.internal --hostname chrome
              cf create-route apps.internal --hostname selenium-hub
      - task: create-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: cf7
          params:
            CF_USERNAME: ((cf-username))
            CF_PASSWORD: ((cf-password))
            ACTION: create-route
          run:
            path: bash
            args:
            - -c
            - |
              cf login -a https://api.london.cloud.service.gov.uk \
                -u $CF_USERNAME -p $CF_PASSWORD \
                -o govuk-pay -s andy
              cf create-app --app-type docker admin-users
              cf create-app --app-type docker card-id
              cf create-app --app-type docker connector
              cf create-app --app-type docker demo-service
              cf create-app --app-type docker direct-debit-connector
              cf create-app --app-type docker direct-debit-frontend
              cf create-app --app-type docker egress
              cf create-app --app-type docker end-to-end
              cf create-app --app-type docker frontend
              cf create-app --app-type docker ledger
              cf create-app --app-type docker postgres
              cf create-app --app-type docker products-ui
              cf create-app --app-type docker products
              cf create-app --app-type docker public-api
              cf create-app --app-type docker public-auth
              cf create-app --app-type docker chrome
              cf create-app --app-type docker selenium-hub
              cf create-app --app-type docker self-service
              cf create-app --app-type docker sqs
              cf create-app --app-type docker stubs

  - name: stop-all-apps
    serial: true
    plan:
      - task: stop-all-apps
        config: &stop-all-apps-config
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: cf7
          params:
            CF_USERNAME: ((cf-username))
            CF_PASSWORD: ((cf-password))
            ACTION: stop
          run:
            path: bash
            args:
            - -c
            - |
              cf login -a https://api.london.cloud.service.gov.uk \
                -u $CF_USERNAME -p $CF_PASSWORD \
                -o govuk-pay -s andy
              cf install-plugin -f do-all
              cf do-all stop {}

  - name: restart-all-apps
    serial: true
    plan:
      - in_parallel:
        - put: andy-paas-space
          params:
            command: restart
            app_name: sqs
        - put: andy-paas-space
          params:
            command: restart
            app_name: postgres
      - in_parallel:
        - put: andy-paas-space
          params:
            command: restart
            app_name: products-ui
        - put: andy-paas-space
          params:
            command: restart
            app_name: demo-service
        - put: andy-paas-space
          params:
            command: restart
            app_name: frontend
        - put: andy-paas-space
          params:
            command: restart
            app_name: ledger
        - put: andy-paas-space
          params:
            command: restart
            app_name: stubs
        - put: andy-paas-space
          params:
            command: restart
            app_name: products
        - put: andy-paas-space
          params:
            command: restart
            app_name: self-service
        - put: andy-paas-space
          params:
            command: restart
            app_name: admin-users
        - put: andy-paas-space
          params:
            command: restart
            app_name: direct-debit-frontend
        - put: andy-paas-space
          params:
            command: restart
            app_name: selenium-hub
        - put: andy-paas-space
          params:
            command: restart
            app_name: direct-debit-connector
        - put: andy-paas-space
          params:
            command: restart
            app_name: connector
        - put: andy-paas-space
          params:
            command: restart
            app_name: egress
        - put: andy-paas-space
          params:
            command: restart
            app_name: public-auth
        - put: andy-paas-space
          params:
            command: restart
            app_name: public-api
        - put: andy-paas-space
          params:
            command: restart
            app_name: chrome
        - put: andy-paas-space
          params:
            command: restart
            app_name: card-id

  - name: switch-off-dev-env
    serial: true
    plan:
      - get: every-night-at-6pm
        trigger: true
      - task: stop-all-apps
        config: *stop-all-apps-config
      - put: andy-dev-env-pipeline
        params:
          options: pause-pipeline -p andy-dev-env

  - name: deploy-admin-users
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: admin-users
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: admin-users }
        params:
          APP: admin-users
  - name: deploy-card-id
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: card-id
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: card-id }
        params:
          APP: card-id
  - name: deploy-connector
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: connector
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: connector }
        params:
          APP: connector
  - name: deploy-direct-debit-connector
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: direct-debit-connector
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: direct-debit-connector }
        params:
          APP: direct-debit-connector
  - name: deploy-direct-debit-frontend
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: direct-debit-frontend
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: direct-debit-frontend }
        params:
          APP: direct-debit-frontend
  - name: deploy-frontend
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: frontend
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: frontend }
        params:
          APP: frontend
  - name: deploy-ledger
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: ledger
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: ledger }
        params:
          APP: ledger
  - name: deploy-products-ui
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: products-ui
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: products-ui }
        params:
          APP: products-ui
  - name: deploy-products
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: products
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: products }
        params:
          APP: products
  - name: deploy-public-api
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: public-api
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: public-api }
        params:
          APP: public-api
  - name: deploy-public-auth
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: public-auth
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: public-auth }
        params:
          APP: public-auth
  - name: deploy-self-service
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - get: self-service
        trigger: true
        params:
          skip_download: true
      - task: deploy-to-paas
        file: deploy-config/tasks/deploy-to-paas.yaml
        input_mapping: { image: self-service }
        params:
          APP: self-service

  - name: deploy-stubs
    serial: true
    plan:
      - get: deploy-config
        trigger: true
        passed: [deploy-tools]
      - in_parallel:
        - get: demo-service
          trigger: true
          params:
            skip_download: true
        - get: stubs
          trigger: true
          params:
            skip_download: true
        - get: end-to-end
          trigger: true
          params:
            skip_download: true
      - in_parallel:
        - task: deploy-demo-service
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: demo-service }
          params:
            APP: demo-service
        - task: deploy-stubs
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: stubs }
          params:
            APP: stubs
        - task: deploy-end-to-end
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: end-to-end }
          params:
            APP: end-to-end

  - name: deploy-tools
    serial: true
    plan:
      - get: deploy-config
        trigger: true
      - in_parallel:
        - get: postgres
          params:
            skip_download: true
        - get: sqs
          params:
            skip_download: true
        - get: egress
          params:
            skip_download: true
        - get: selenium-hub
          params:
            skip_download: true
        - get: chrome
          params:
            skip_download: true
      - in_parallel:
        - task: deploy-postgres-to-paas
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: postgres }
          params:
            APP: postgres
        - task: deploy-sqs-to-paas
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: sqs }
          params:
            APP: sqs
        - task: deploy-egress-to-paas
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: egress }
          params:
            APP: egress
        - task: deploy-selenium-hub-to-paas
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: selenium-hub }
          params:
            APP: selenium-hub
        - task: deploy-chrome-to-paas
          file: deploy-config/tasks/deploy-to-paas.yaml
          input_mapping: { image: chrome }
          params:
            APP: chrome
